export const GET_PLANTS_ACTION = 'GET_PLANTS_ACTION';
export const GET_PLANTS_LOADING = 'GET_PLANTS_LOADING';
export const GET_PLANTS_ERROR = 'GET_PLANTS_ERROR';

export const WATER_PLANT_ACTION = 'WATER_PLANT_ACTION';